name: Gatsby Deploy

on:
  push:
    branches: master

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Config
        run: |
          git config --global user.email "example@example.example"
          git config --global user.name "example"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: |
          npm install
      - name: Deploy
        run: npm run deploy:ci
